# Generated by Django 5.2.9 on 2025-12-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppinig',
            new_name='Topping',
        ),
    ]
